In [9]:
import re
import pandas as pd

In [10]:
f = open('WhatsApp Chat with IIT Raisen Road.txt','r',encoding = 'utf-8')

In [11]:
data = f.read()

In [12]:
print(data)

7/25/23, 7:16 AM - Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.
7/22/23, 1:10 PM - ~ Tanishq Kirar created group "LNCTS CSE "C" UNOFFICIAL "
7/25/23, 7:16 AM - You joined using this group's invite link
7/25/23, 7:54 AM - +91 93049 97409 joined using this group's invite link
7/25/23, 7:57 AM - Sahil Tale Lnct joined using this group's invite link
7/25/23, 8:24 AM - +91 84628 47414 joined using this group's invite link
7/25/23, 8:40 AM - Akash Lnct joined using this group's invite link
7/25/23, 8:45 AM - +91 62623 05152 joined using this group's invite link
7/25/23, 9:45 AM - Saurav LNCT joined using this group's invite link
7/25/23, 10:25 AM - +91 77488 92636 joined using this group's invite link
7/25/23, 10:50 AM - +91 83059 85242 joined using this group's invite link
7/25/23, 10:55 AM - +91 62641 71298 joined using this group's invite link
7/25/23, 11:17 AM - Vanshit Lncts joined using this group's invite link
7/25/23, 11:18 AM - +91 88713 77009 joined using this group's invite link
7/25/23, 11:31 AM - Saloni Lnct joined using this group's invite link
7/25/23, 11:50 AM - +91 83496 44567 joined using this group's invite link
7/25/23, 12:43 PM - ~ Tanishq Kirar changed this group's icon
7/25/23, 12:43 PM - ~ Tanishq Kirar removed ~ Lokesh Dhote
7/25/23, 12:48 PM - New members need admin approval to join this group.
7/25/23, 12:48 PM - As a member, you can join groups in the community and get admin updates
Your profile is visible to admins
7/25/23, 12:48 PM - New members need admin approval to join this group.
7/25/23, 12:54 PM - ~ Tanishq Kirar removed this group from the community "LNCT'S 4th SEMESTER"
7/25/23, 2:43 PM - +91 88271 27187 joined using this group's invite link
7/25/23, 2:43 PM - +91 97533 34422 turned off admin approval to join this group.
7/25/23, 9:43 PM - Rudrasksh Lncts joined using this group's invite link
7/26/23, 2:46 PM - +91 87701 54306 joined using this group's invite link
7/26/23, 11:23 PM - +91 88275 58358 joined using this group's invite link
7/27/23, 1:10 AM - +91 87709 96018 joined using this group's invite link
7/31/23, 8:17 AM - Nishant Lnct joined using this group's invite link
8/2/23, 10:34 PM - Shreyansh Lnct: 🎉 Hello, Tech Enthusiasts! 🌟💻

We're thrilled to invite you to our brand new GDSC group! 🚀🎊 Let's make this tech journey together filled with knowledge, innovation, and camaraderie! 🌈💡

Join us to explore the latest technologies, collaborate on exciting projects, and build lasting connections with like-minded individuals. 🤝🚀

Click on the link below to join the fun:

https://chat.whatsapp.com/Ii1FOH8Tgr03cGfAyKqgcA

Welcome aboard! 🎉🎓

*PS: We have dissolved all previous WhatsApp groups of GDSC-LNCTS. Therefore, you won't receive any updates there.*
8/8/23, 10:08 AM - Shreyansh Lnct: Hi everyone,
I am Shreyansh one of your classmate I heartily welcome all of you in our class. Kindly share this group link to your known other classmates .
8/8/23, 10:09 AM - Shreyansh Lnct: POLL:
How many of you are coming to college?
OPTION: On 10 August (0 votes)
OPTION: After 15 August (5 votes)

8/8/23, 1:53 PM - +91 97533 34422: Who are not from section c leave the group
8/9/23, 7:50 PM - +91 99931 34544 joined using this group's invite link
8/11/23, 3:58 AM - +91 78988 30699 changed their phone number to a new number. Tap to message or add the new number.
8/11/23, 4:01 AM - +91 81209 75995 changed to +91 78988 30699
8/11/23, 4:03 AM - +91 78988 30699 changed their phone number to a new number. Tap to message or add the new number.
8/11/23, 4:10 AM - +91 81209 75995 changed to +91 78988 30699
8/12/23, 10:08 AM - Harshita Lncts joined using this group's invite link
8/18/23, 1:16 PM - Vansh Lncts: This message was deleted
8/20/23, 6:34 PM - +91 72474 15933: Follow this link to join my WhatsApp group: https://chat.whatsapp.com/JRNW7i6imHSFARQAUl6ilG
8/20/23, 9:13 PM - Suyash Lnct joined using this group's invite link
8/28/23, 4:59 PM - +91 93294 25001 joined using this group's invite link
9/3/23, 10:20 AM - +91 94246 48150: Hello Future Core Team Members! 🌟

Exciting news! Quality Circle Forum Of India is coming to our college, and we're on the lookout for passionate individuals like YOU to join the core team! 🚀

This club is formed under the supervision of:
QCFI Bhopal Chapter Official
Dr.Anurag S D Rai (Director,KLIC-LNCT)
Mr.Vishnu Prasad Markam (Manager,KLIC-LNCT)

🚀Perks:
🔹Promotion of teamwork.
🔹️Develops Student positive attitudes.
🔹️Positive working environment.
🔹️Increased quality and productivity.
🔹️Increased Network.
🔹️Developing Problem         Solving Skills.

If you're eager to be a part of something extraordinary, share your ideas, and take the lead, this is YOUR opportunity! We need dedicated students who can help shape our community's future.

👉 Google Form Link-
    https://docs.google.com/forms/d/e/1FAIpQLSfVtVWQQOa-KhvQcwT2jdKfvPsXtu6hluv7bCI9eZE_mGOlSw/viewform?usp=sf_link

Please take a moment to fill out this Google Form to express your interest and tell us why you'd be an awesome addition to the core team. Your unique talents and enthusiasm could be the driving force behind our college's vibrant community.

Let's embark on this exciting journey together and make a difference on campus! 🎓

*For More Information read our Google form description carefully.*

Thank you for being a part of our community's growth!

Join our Whatsapp group for future Updates:
https://chat.whatsapp.com/Ev9SMJ5d01I9Wm4QPsMeJF

Join Us On Instagram-
https://instagram.com/kqcfi_lnct?igshid=NjIwNzIyMDk2Mg==

Best regards,
@Parth_Sahu07
Head Coordinator
KQCFI
9/5/23, 10:54 AM - Samriddh Lnct: This message was deleted
9/6/23, 10:21 AM - Rohit Lncts joined using this group's invite link
9/6/23, 1:51 PM - +91 94246 48150: https://l.linklyhq.com/l/1tVfZ
9/6/23, 3:34 PM - +91 77800 50256 joined using this group's invite link
9/6/23, 4:24 PM - +91 88155 57172: <Media omitted>
9/6/23, 4:24 PM - +91 88155 57172: <Media omitted>
9/6/23, 4:24 PM - +91 88155 57172: <Media omitted>
9/6/23, 4:26 PM - +91 93294 25001: <Media omitted>
9/6/23, 4:26 PM - +91 93294 25001: <Media omitted>
9/6/23, 4:26 PM - +91 93294 25001: <Media omitted>
9/6/23, 4:26 PM - +91 93294 25001: <Media omitted>
9/6/23, 4:28 PM - +91 93993 58083 joined using this group's invite link
9/6/23, 4:46 PM - Shantanu Lncts joined using this group's invite link
9/6/23, 7:20 PM - Rahul Lncts joined using this group's invite link
9/8/23, 11:48 AM - +91 75092 58993 joined using this group's invite link
9/8/23, 11:49 AM - +91 89624 84906 joined using this group's invite link
9/8/23, 5:48 PM - +91 62641 71298: <Media omitted>
9/8/23, 10:32 PM - Deepak Lncts joined using this group's invite link
9/11/23, 11:59 AM - Rohit Lncts: <Media omitted>
9/12/23, 6:35 PM - +91 88155 57172: <Media omitted>
9/12/23, 7:51 PM - +91 88399 24082 joined using this group's invite link
9/13/23, 4:05 PM - +91 88155 57172: 1st and 3rd unit or main aayenge questions
9/13/23, 4:05 PM - +91 88155 57172: Discrete structure main
9/13/23, 4:05 PM - +91 88155 57172: <Media omitted>
9/13/23, 4:06 PM - Harshita Lncts: Main?
9/13/23, 4:06 PM - +91 88155 57172: Set theory,relation
Or
propositional logic
9/13/23, 4:06 PM - Harshita Lncts: Ye toh mam padhayi hi nhi hai
9/13/23, 4:06 PM - Harshita Lncts: 😭
9/13/23, 4:06 PM - +91 88155 57172: Means in
9/13/23, 4:07 PM - Shantanu Lncts: Bhai 3rd unit hua khan hai?🥲
9/13/23, 4:07 PM - +91 88155 57172: Unhone bolna hai 3rd unit easy hai
9/13/23, 4:07 PM - Harshita Lncts: Ok
9/13/23, 4:07 PM - +91 88155 57172: And lnct MAIN se paper bana hai isliye
9/13/23, 4:07 PM - Shantanu Lncts: Han to?
Khudh se krna hoga?🥲
9/13/23, 4:09 PM - +91 88399 24082: 🙄
9/13/23, 6:33 PM - Vansh Lncts: Ma'am ne bola hai ki discrete structure me 1unit full aaegi and 3rd unit ke kuch topics aaenge jo class me karva diye hai
9/13/23, 6:34 PM - Harshita Lncts: 3rd unit k kon se topic karaye hai class me
9/13/23, 6:34 PM - Harshita Lncts: Kuch batayega ?
9/13/23, 6:34 PM - Vansh Lncts: Nope
9/13/23, 6:34 PM - Harshita Lncts: 🥲
9/13/23, 6:34 PM - +91 93294 25001: Yee kabh hua🥲
9/13/23, 6:36 PM - +91 88399 24082: Sapne me🙂
9/13/23, 7:12 PM - Sahil Tale Lnct: Kisi ke paas purane saalo ke mid sem paper hai kya manual me jo diye hai uske alawa
9/13/23, 9:26 PM - +91 88399 24082: No
9/13/23, 11:16 PM - Vansh Lncts: POLL:
Kl koee college jayega ?
OPTION: Yes (0 votes)
OPTION: No (19 votes)

9/14/23, 5:41 PM - Sahil Tale Lnct: Bhai kisi ke paas environmental ke notes hai kya
9/14/23, 7:11 PM - +91 73015 06516: <Media omitted>
9/14/23, 7:11 PM - +91 73015 06516: <Media omitted>
9/19/23, 7:25 PM - +91 62077 21723 joined using this group's invite link
9/22/23, 6:20 AM - +91 97717 53350 joined using this group's invite link
9/22/23, 7:49 PM - +91 72474 15933: <Media omitted>
9/22/23, 7:49 PM - +91 72474 15933: pls kisi ko mile contact me
9/23/23, 12:32 PM - Vansh Lncts: <Media omitted>
9/23/23, 1:23 PM - Shreyansh Lnct: <Media omitted>
9/23/23, 1:23 PM - Shreyansh Lnct: <Media omitted>
9/24/23, 1:42 PM - +91 94246 48150: <Media omitted>
9/26/23, 11:47 AM - Rohit Lncts: <Media omitted>
9/26/23, 11:47 AM - Rohit Lncts: <Media omitted>
9/26/23, 11:47 AM - Rohit Lncts: <Media omitted>
9/26/23, 11:48 AM - Rohit Lncts: <Media omitted>
9/26/23, 8:37 PM - +91 73896 14480: 📢 Exciting Opportunity at *Kalchuri Entrepreneurs Club!* We are currently looking for a talented *Graphic Designer* to join our team. If you have a passion for creativity and design, we want to hear from you!

*Position: Graphic Designer*

To apply, please click on the link below:

https://forms.gle/6JNpM5LFDd3TpDSk6

Don't miss out on this chance to be part of our dynamic team. Your design skills could be the missing piece we're looking for! 🖌️🎨 #JobOpening #GraphicDesigner #ApplyNow
9/27/23, 2:23 PM - +91 62675 56439: <Media omitted>
9/27/23, 2:27 PM - Harshita Lncts: Kya hona hai isme ?
9/27/23, 6:13 PM - +91 62675 56439: Collage fest h
9/27/23, 6:19 PM - +91 62675 56439: Non food passes are available now !!!

Price: 449/-
9/29/23, 9:23 PM - +91 62651 77903 joined using this group's invite link
9/29/23, 9:24 PM - +91 62651 77903: POLL:
Kal college Jana h ki nhi
OPTION: Yes (0 votes)
OPTION: No (22 votes)

9/29/23, 9:24 PM - +91 62651 77903: Sorry us group m mentor,hod the
9/29/23, 9:26 PM - +91 88399 24082: Hmm
9/29/23, 9:27 PM - +91 62651 77903: Koi nhi jayga to attendance count nhi hoygi
9/29/23, 9:27 PM - +91 88399 24082: To fir koi mat jao
9/29/23, 9:39 PM - +91 94246 48150: "Hello Everyone,

I hope you're doing well! I wanted to let you know that if you attended the Chevening scholarship seminar on September 26th and need to confirm your attendance, please join the official group of KQCFI (Kalchuri Quality Circle Forum of India ) . This is the official group where we will be sharing attendance to those who filled the forms or attended the event

Join KQCFI Group: https://chat.whatsapp.com/Ev9SMJ5d01I9Wm4QPsMeJF

Please make sure to join the group as soon as possible to get the attendance . If you have any questions or need assistance, feel free to reach out to me.

Thank you, and best of luck with your Chevening scholarship application!

Warm regards,
Parth Sahu
9/29/23, 11:48 PM - +91 62675 56439: <Media omitted>
9/30/23, 5:34 PM - Vashu Lnct: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/3/23, 2:32 PM - +91 93993 58083: <Media omitted>
10/4/23, 7:52 PM - +91 72474 15933: <Media omitted>
10/6/23, 7:51 PM - +91 88173 79585: <Media omitted>
10/9/23, 3:04 PM - +91 94246 48150: 🌟 Join the KHADI MAHOTSAV Quiz for a Chance to Win Exciting Prizes! 🎉

Hello there!

We're thrilled to invite you to the KHADI MAHOTSAV Quiz, where knowledge meets excitement and rewards! 📚🏆

🔥 Get ready to test your knowledge on a wide range of topics while having a blast! Here's what you need to know:

📌 *Date: [09 OCTOBER 2023] TODAY*
🕒 *Time: [02:30- 5:00]*
📍 *Venue: [LNCTE AUDITORIUM ]*

✨ Why should you participate?

Exciting Prizes: We've got some amazing prizes lined up for our quiz champions! From gift vouchers to exclusive Khadi products, there's something for everyone.

Boost Your Knowledge: Our quiz questions cover a variety of topics, so you're bound to learn something new while having fun.

Connect with Khadi Enthusiasts: Meet like-minded individuals who share your passion for Khadi and sustainable living.

Support a Great Cause: By participating, you contribute to the promotion of Khadi, an eco-friendly and socially responsible textile.

For registration fill this Google form -
https://forms.gle/CtH81uZDk2zwuLzGA
10/10/23, 9:46 PM - +91 62651 77903: This message was deleted
10/12/23, 3:47 PM - +91 88399 24082: This message was deleted
10/12/23, 3:47 PM - +91 88399 24082: <Media omitted>
10/12/23, 3:47 PM - +91 88399 24082: <Media omitted>
10/12/23, 3:48 PM - +91 88399 24082: <Media omitted>
10/13/23, 2:52 PM - Shantanu Lncts: POLL:
Mass Bunk tomorrow
OPTION: Yes (18 votes)
OPTION: No (0 votes)
OPTION: Bhai meri attendance low hai mjhe aana prega 🥲 (5 votes)

10/13/23, 2:53 PM - Shantanu Lncts: Bhai kal ND vs Pakistan ka match hai soch lena ek baar vote krne se phle sab 🙂
10/13/23, 2:54 PM - +91 88399 24082: 🇮🇳
10/13/23, 4:07 PM - Shantanu Lncts: Note- Mass bunk me ksi ki attendance nato badhegi nato ghategi to mass bunk kr skte hain
10/13/23, 10:48 PM - Yuval Lnct: This message was deleted
10/14/23, 10:33 AM - +91 94246 48150: ‎Open this link to join my WhatsApp Group: https://chat.whatsapp.com/KjFJ30VehOpHWRnRi1rbgF
10/14/23, 11:01 AM - Shantanu Lncts: Bhai koi gya hai ky cls??
10/14/23, 12:50 PM - Vansh Lncts: Joke karta hai
10/15/23, 2:58 PM - +91 94246 48150: "🔍 Join Our Quality Circle ! 🔍

Hello everyone,

Are you passionate about how things actually work at industrial plants, how things work at ground level , practical implementation and teamwork?

✨ We've got an exciting opportunity for you! We are thrilled to invite you to join our Quality Circle , which is proudly associated with renowned brands like Godrej, Hershey's, Volvo, and Eicher.

🌟 What You'll Get:

✅- Stay updated on all the latest activities, events, and initiatives of our Quality Circle, in collaboration with industry leaders like Godrej, Hershey's, Volvo, and Eicher.

✅- Gain exclusive opportunities to interact with professionals from these esteemed companies, allowing you to network and gain exposure to real-world industry practices.

✅- Get access to valuable resources and insights on quality improvement.

✅- Connect with like-minded individuals who share your passion for excellence.

Join us in our journey towards enhancing quality and making a positive impact, with the support of industry giants. To join, simply click the link below:

https://chat.whatsapp.com/Ev9SMJ5d01I9Wm4QPsMeJF
Let's work together to make a difference in our college and industry through quality initiatives. Your contribution matters, and the chance to interact with professionals from these companies is a unique opportunity! 🌟

See you in the group!

Best regards,
Team"K-QCFI".
10/16/23, 9:48 PM - +91 79996 77206 joined using this group's invite link
10/16/23, 9:50 PM - +91 88252 16823 joined using this group's invite link
10/16/23, 9:49 PM - +91 79996 77206: <Media omitted>
10/16/23, 11:04 PM - Shalinder Pathak Lnct joined using this group's invite link
10/16/23, 11:08 PM - +91 97536 63891 joined using this group's invite link
10/18/23, 11:48 AM - Shantanu Lncts: Bhai C type charger hai ky class me ksi ke pass av????
Hai to de dena bhai log phn bs 18% charge hai🥲
10/18/23, 12:03 PM - ~ Rohan Choudhary added ~ Venkat
10/18/23, 1:21 PM - +91 62077 21723: This message was deleted
10/18/23, 1:21 PM - +91 62077 21723: This message was deleted
10/19/23, 9:32 PM - Srishti Hazra: <Media omitted>
10/19/23, 9:33 PM - Srishti Hazra: <Media omitted>
10/20/23, 10:45 AM - Shantanu Lncts: https://docs.google.com/forms/d/e/1FAIpQLSdm6_ZQUUbjClVUr_mPoRMB4VzruMVK0Hi6-pAc_PloY1-FFg/viewform?vc=0&c=0&w=1&flr=0
10/20/23, 11:26 AM - ~ vivek indorkar added ~ Anurag Rajput
10/20/23, 12:18 PM - ~ Anurag Rajput added ~ Raaz❤️
10/21/23, 12:23 PM - +91 77488 92636: This message was deleted
10/21/23, 12:26 PM - Shantanu Lncts: Bhai mai to lunch phle hi ni aya hun 😂
10/21/23, 12:26 PM - Shantanu Lncts: Monday ka ky scene hai?
Kon kon aa rha?
10/21/23, 12:30 PM - Sumit Lncts: Monday ko mass bunk hai
10/21/23, 12:41 PM - Shantanu Lncts: POLL:
Monday mass bunk?
OPTION: Yes (40 votes)
OPTION: No (1 vote)

10/21/23, 12:42 PM - Shantanu Lncts: Bhai sab koi poll daal dena or real dalna
Saturday k trh mt krna us din 22 baache aa gye the
Agr koi ni ayega to attendance ksi ki jyegi bhi ni to nuksaan ksi ka ni hai
10/21/23, 12:43 PM - Shantanu Lncts: Or aise bhi Data digital or do Oops hai us din🥲
10/21/23, 12:46 PM - Vansh Lncts: declare kar do jo jayega usko baad me dekh lenghe
10/21/23, 12:47 PM - ~ Anurag Rajput added ~ Aryan 💫
10/21/23, 12:52 PM - Sumit Lncts: This message was deleted
10/21/23, 12:52 PM - Sumit Lncts: Bilkul
10/21/23, 12:56 PM - ~ satyam added ~ SATYAM ✨
10/21/23, 12:56 PM - Vansh Lncts: Kam se Kam Pole pe clear kar do jisko Jana he padega
10/21/23, 12:58 PM - +91 91311 08306: me to aaunga koi aao ya na aao
10/21/23, 1:12 PM - Shantanu Lncts: Cancel hi kr dete hain bhai
Ye log nahi manega
Aa hi jayega
To mtlb nahi rhega mass bunk ka
10/21/23, 1:14 PM - +91 99053 44129: Shi bola bhai ,,sb haramkhor h nii manege
10/21/23, 1:14 PM - +91 91311 08306: i am just kidding me bhi nai raha
10/21/23, 1:15 PM - +91 79996 77206: Areeh... Nhi aate h... Na attendance badhegi... Or na hi km hogi
10/21/23, 1:16 PM - +91 77229 36199: Andi bandi shandi krdo
10/21/23, 1:16 PM - Shantanu Lncts: <Media omitted>
10/21/23, 1:16 PM - Shantanu Lncts: Phir bhi sab ayega bc
10/21/23, 1:16 PM - Shantanu Lncts: You know what i mean☠️
10/21/23, 1:16 PM - Sumit Lncts: Rhne de inka kuch nhi ho sakta
10/21/23, 1:16 PM - +91 91311 08306: This message was deleted
10/21/23, 1:16 PM - +91 99053 44129: Apan to bol rhe h Are h pura mehnat se dsa padhenge or placement lenge
10/21/23, 1:17 PM - Shantanu Lncts: @917722936199 glt poll daal diya bsdk tu
10/21/23, 1:17 PM - Shantanu Lncts: 🤦‍♂️
10/21/23, 1:17 PM - Sumit Lncts: ...
10/21/23, 1:17 PM - +91 77229 36199: Are dekha ni 🥲
10/21/23, 1:18 PM - Shantanu Lncts: ANDI MANDI SHANDI JO MONDAY KO AAYA..
Aage sab smjhdar ho
10/21/23, 2:51 PM - Shekhar LNCT: LNCTS Khel Mohotsav Badminton Tournament 2023

We are pleased to announce a Badminton Tournament on 26/10/2023.

Entry Fee: ₹50

Participants are requested to register in advance. Grab your rackets and showcase your skills!

For further details and registration, please contact the following:
(Faculty coordinator)
Amol Upadhyay - 9893003004

(Student coordinators)
Shekhar Suman - 6204082621
Yuval Varke - 9724614728


Thank you.
10/22/23, 5:41 PM - +91 93291 37551: This message was deleted
10/22/23, 5:53 PM - +91 93291 37551: To participate, please fill out this form: https://forms.gle/VHEZyBE5xfR6KVHv8

LNCTS CSE CARROM TOURNAMENT
🏆 Get Ready to Crown the Queen! 🏆

📣 Exciting News LNCTS Students! 📣

👑 LNCTS Carrom Championship - October 27th! 👑

🤩 Are you ready to showcase your carrom skills and seize amazing prizes? 🤩

📅 Mark your calendars for 27th October
📍 LNCTS Campus

🤑 Registration Fee: Only 50 Rupees

🏆 Prizes await the Carrom Queens and Kings! 🏆


In [13]:
pattern = r'\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s?[APM]*\s-\s'

In [14]:
messages = re.split(pattern, data)[1:]
messages

['Messages and calls are end-to-end encrypted. No one outside of this chat, not even WhatsApp, can read or listen to them. Tap to learn more.\n',
 '~\u202fTanishq Kirar created group "LNCTS CSE "C" UNOFFICIAL "\n',
 "You joined using this group's invite link\n",
 "+91 93049 97409 joined using this group's invite link\n",
 "Sahil Tale Lnct joined using this group's invite link\n",
 "+91 84628 47414 joined using this group's invite link\n",
 "Akash Lnct joined using this group's invite link\n",
 "+91 62623 05152 joined using this group's invite link\n",
 "Saurav LNCT joined using this group's invite link\n",
 "+91 77488 92636 joined using this group's invite link\n",
 "+91 83059 85242 joined using this group's invite link\n",
 "+91 62641 71298 joined using this group's invite link\n",
 "Vanshit Lncts joined using this group's invite link\n",
 "+91 88713 77009 joined using this group's invite link\n",
 "Saloni Lnct joined using this group's invite link\n",
 "+91 83496 44567 joined using this group's invite link\n",
 "~\u202fTanishq Kirar changed this group's icon\n",
 '~\u202fTanishq Kirar removed ~\u202fLokesh Dhote\n',
 'New members need admin approval to join this group.\n',
 'As a member, you can join groups in the community and get admin updates\nYour profile is visible to admins\n',
 'New members need admin approval to join this group.\n',
 '~\u202fTanishq Kirar removed this group from the community "LNCT\'S 4th SEMESTER"\n',
 "+91 88271 27187 joined using this group's invite link\n",
 '+91 97533 34422 turned off admin approval to join this group.\n',
 "Rudrasksh Lncts joined using this group's invite link\n",
 "+91 87701 54306 joined using this group's invite link\n",
 "+91 88275 58358 joined using this group's invite link\n",
 "+91 87709 96018 joined using this group's invite link\n",
 "Nishant Lnct joined using this group's invite link\n",
 "Shreyansh Lnct: 🎉 Hello, Tech Enthusiasts! 🌟💻\n\nWe're thrilled to invite you to our brand new GDSC group! 🚀🎊 Let's make this tech journey together filled with knowledge, innovation, and camaraderie! 🌈💡\n\nJoin us to explore the latest technologies, collaborate on exciting projects, and build lasting connections with like-minded individuals. 🤝🚀\n\nClick on the link below to join the fun:\n\nhttps://chat.whatsapp.com/Ii1FOH8Tgr03cGfAyKqgcA\n\nWelcome aboard! 🎉🎓\n\n*PS: We have dissolved all previous WhatsApp groups of GDSC-LNCTS. Therefore, you won't receive any updates there.*\n",
 'Shreyansh Lnct: Hi everyone,\nI am Shreyansh one of your classmate I heartily welcome all of you in our class. Kindly share this group link to your known other classmates .\n',
 'Shreyansh Lnct: POLL:\nHow many of you are coming to college?\nOPTION: On 10 August (0 votes)\nOPTION: After 15 August (5 votes)\n\n',
 '+91 97533 34422: Who are not from section c leave the group\n',
 "+91 99931 34544 joined using this group's invite link\n",
 '+91 78988 30699 changed their phone number to a new number. Tap to message or add the new number.\n',
 '+91\xa081209\xa075995 changed to +91\xa078988\xa030699\n',
 '+91 78988 30699 changed their phone number to a new number. Tap to message or add the new number.\n',
 '+91\xa081209\xa075995 changed to +91\xa078988\xa030699\n',
 "Harshita Lncts joined using this group's invite link\n",
 'Vansh Lncts: This message was deleted\n',
 '+91 72474 15933: Follow this link to join my WhatsApp group: https://chat.whatsapp.com/JRNW7i6imHSFARQAUl6ilG\n',
 "Suyash Lnct joined using this group's invite link\n",
 "+91 93294 25001 joined using this group's invite link\n",
 "+91 94246 48150: Hello Future Core Team Members! 🌟\n\nExciting news! Quality Circle Forum Of India is coming to our college, and we're on the lookout for passionate individuals like YOU to join the core team! 🚀\n\nThis club is formed under the supervision of:\nQCFI Bhopal Chapter Official\nDr.Anurag S D Rai (Director,KLIC-LNCT)\nMr.Vishnu Prasad Markam (Manager,KLIC-LNCT)\n\n🚀Perks:\n🔹Promotion of teamwork.\n🔹️Develops Student positive attitudes.\n🔹️Positive working environment.\n🔹️Increased quality and productivity.\n🔹️Increased Network.\n🔹️Developing Problem         Solving Skills.\n\nIf you're eager to be a part of something extraordinary, share your ideas, and take the lead, this is YOUR opportunity! We need dedicated students who can help shape our community's future.\n\n👉 Google Form Link-\n    https://docs.google.com/forms/d/e/1FAIpQLSfVtVWQQOa-KhvQcwT2jdKfvPsXtu6hluv7bCI9eZE_mGOlSw/viewform?usp=sf_link\n\nPlease take a moment to fill out this Google Form to express your interest and tell us why you'd be an awesome addition to the core team. Your unique talents and enthusiasm could be the driving force behind our college's vibrant community.\n\nLet's embark on this exciting journey together and make a difference on campus! 🎓\n\n*For More Information read our Google form description carefully.*\n\nThank you for being a part of our community's growth!\n\nJoin our Whatsapp group for future Updates:\nhttps://chat.whatsapp.com/Ev9SMJ5d01I9Wm4QPsMeJF\n\nJoin Us On Instagram-\nhttps://instagram.com/kqcfi_lnct?igshid=NjIwNzIyMDk2Mg==\n\nBest regards,\n@Parth_Sahu07\nHead Coordinator\nKQCFI\n",
 'Samriddh Lnct: This message was deleted\n',
 "Rohit Lncts joined using this group's invite link\n",
 '+91 94246 48150: https://l.linklyhq.com/l/1tVfZ\n',
 "+91 77800 50256 joined using this group's invite link\n",
 '+91 88155 57172: <Media omitted>\n',
 '+91 88155 57172: <Media omitted>\n',
 '+91 88155 57172: <Media omitted>\n',
 '+91 93294 25001: <Media omitted>\n',
 '+91 93294 25001: <Media omitted>\n',
 '+91 93294 25001: <Media omitted>\n',
 '+91 93294 25001: <Media omitted>\n',
 "+91 93993 58083 joined using this group's invite link\n",
 "Shantanu Lncts joined using this group's invite link\n",
 "Rahul Lncts joined using this group's invite link\n",
 "+91 75092 58993 joined using this group's invite link\n",
 "+91 89624 84906 joined using this group's invite link\n",
 '+91 62641 71298: <Media omitted>\n',
 "Deepak Lncts joined using this group's invite link\n",
 'Rohit Lncts: <Media omitted>\n',
 '+91 88155 57172: <Media omitted>\n',
 "+91 88399 24082 joined using this group's invite link\n",
 '+91 88155 57172: 1st and 3rd unit or main aayenge questions\n',
 '+91 88155 57172: Discrete structure main\n',
 '+91 88155 57172: <Media omitted>\n',
 'Harshita Lncts: Main?\n',
 '+91 88155 57172: Set theory,relation\nOr\npropositional logic\n',
 'Harshita Lncts: Ye toh mam padhayi hi nhi hai\n',
 'Harshita Lncts: 😭\n',
 '+91 88155 57172: Means in\n',
 'Shantanu Lncts: Bhai 3rd unit hua khan hai?🥲\n',
 '+91 88155 57172: Unhone bolna hai 3rd unit easy hai\n',
 'Harshita Lncts: Ok\n',
 '+91 88155 57172: And lnct MAIN se paper bana hai isliye\n',
 'Shantanu Lncts: Han to?\nKhudh se krna hoga?🥲\n',
 '+91 88399 24082: 🙄\n',
 "Vansh Lncts: Ma'am ne bola hai ki discrete structure me 1unit full aaegi and 3rd unit ke kuch topics aaenge jo class me karva diye hai\n",
 'Harshita Lncts: 3rd unit k kon se topic karaye hai class me\n',
 'Harshita Lncts: Kuch batayega ?\n',
 'Vansh Lncts: Nope\n',
 'Harshita Lncts: 🥲\n',
 '+91 93294 25001: Yee kabh hua🥲\n',
 '+91 88399 24082: Sapne me🙂\n',
 'Sahil Tale Lnct: Kisi ke paas purane saalo ke mid sem paper hai kya manual me jo diye hai uske alawa\n',
 '+91 88399 24082: No\n',
 'Vansh Lncts: POLL:\nKl koee college jayega ?\nOPTION: Yes (0 votes)\nOPTION: No (19 votes)\n\n',
 'Sahil Tale Lnct: Bhai kisi ke paas environmental ke notes hai kya\n',
 '+91 73015 06516: <Media omitted>\n',
 '+91 73015 06516: <Media omitted>\n',
 "+91 62077 21723 joined using this group's invite link\n",
 "+91 97717 53350 joined using this group's invite link\n",
 '+91 72474 15933: <Media omitted>\n',
 '+91 72474 15933: pls kisi ko mile contact me\n',
 'Vansh Lncts: <Media omitted>\n',
 'Shreyansh Lnct: <Media omitted>\n',
 'Shreyansh Lnct: <Media omitted>\n',
 '+91 94246 48150: <Media omitted>\n',
 'Rohit Lncts: <Media omitted>\n',
 'Rohit Lncts: <Media omitted>\n',
 'Rohit Lncts: <Media omitted>\n',
 'Rohit Lncts: <Media omitted>\n',
 "+91 73896 14480: 📢 Exciting Opportunity at *Kalchuri Entrepreneurs Club!* We are currently looking for a talented *Graphic Designer* to join our team. If you have a passion for creativity and design, we want to hear from you!\n\n*Position: Graphic Designer*\n\nTo apply, please click on the link below:\n\nhttps://forms.gle/6JNpM5LFDd3TpDSk6\n\nDon't miss out on this chance to be part of our dynamic team. Your design skills could be the missing piece we're looking for! 🖌️🎨 #JobOpening #GraphicDesigner #ApplyNow\n",
 '+91 62675 56439: <Media omitted>\n',
 'Harshita Lncts: Kya hona hai isme ?\n',
 '+91 62675 56439: Collage fest h\n',
 '+91 62675 56439: Non food passes are available now !!!  \n\nPrice: 449/-\n',
 "+91 62651 77903 joined using this group's invite link\n",
 '+91 62651 77903: POLL:\nKal college Jana h ki nhi\nOPTION: Yes (0 votes)\nOPTION: No (22 votes)\n\n',
 '+91 62651 77903: Sorry us group m mentor,hod the\n',
 '+91 88399 24082: Hmm\n',
 '+91 62651 77903: Koi nhi jayga to attendance count nhi hoygi\n',
 '+91 88399 24082: To fir koi mat jao\n',
 '+91 94246 48150: "Hello Everyone,\n\nI hope you\'re doing well! I wanted to let you know that if you attended the Chevening scholarship seminar on September 26th and need to confirm your attendance, please join the official group of KQCFI (Kalchuri Quality Circle Forum of India ) . This is the official group where we will be sharing attendance to those who filled the forms or attended the event \n\nJoin KQCFI Group: https://chat.whatsapp.com/Ev9SMJ5d01I9Wm4QPsMeJF\n\nPlease make sure to join the group as soon as possible to get the attendance . If you have any questions or need assistance, feel free to reach out to me.\n\nThank you, and best of luck with your Chevening scholarship application!\n\nWarm regards,\nParth Sahu\n',
 '+91 62675 56439: <Media omitted>\n',
 'Vashu Lnct: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 93993 58083: <Media omitted>\n',
 '+91 72474 15933: <Media omitted>\n',
 '+91 88173 79585: <Media omitted>\n',
 "+91 94246 48150: 🌟 Join the KHADI MAHOTSAV Quiz for a Chance to Win Exciting Prizes! 🎉\n\nHello there!\n\nWe're thrilled to invite you to the KHADI MAHOTSAV Quiz, where knowledge meets excitement and rewards! 📚🏆\n\n🔥 Get ready to test your knowledge on a wide range of topics while having a blast! Here's what you need to know:\n\n📌 *Date: [09 OCTOBER 2023] TODAY*\n🕒 *Time: [02:30- 5:00]*\n📍 *Venue: [LNCTE AUDITORIUM ]*\n\n✨ Why should you participate?\n\nExciting Prizes: We've got some amazing prizes lined up for our quiz champions! From gift vouchers to exclusive Khadi products, there's something for everyone.\n\nBoost Your Knowledge: Our quiz questions cover a variety of topics, so you're bound to learn something new while having fun.\n\nConnect with Khadi Enthusiasts: Meet like-minded individuals who share your passion for Khadi and sustainable living.\n\nSupport a Great Cause: By participating, you contribute to the promotion of Khadi, an eco-friendly and socially responsible textile.\n\nFor registration fill this Google form - \nhttps://forms.gle/CtH81uZDk2zwuLzGA\n",
 '+91 62651 77903: This message was deleted\n',
 '+91 88399 24082: This message was deleted\n',
 '+91 88399 24082: <Media omitted>\n',
 '+91 88399 24082: <Media omitted>\n',
 '+91 88399 24082: <Media omitted>\n',
 'Shantanu Lncts: POLL:\nMass Bunk tomorrow\nOPTION: Yes (18 votes)\nOPTION: No (0 votes)\nOPTION: Bhai meri attendance low hai mjhe aana prega 🥲 (5 votes)\n\n',
 'Shantanu Lncts: Bhai kal ND vs Pakistan ka match hai soch lena ek baar vote krne se phle sab 🙂\n',
 '+91 88399 24082: 🇮🇳\n',
 'Shantanu Lncts: Note- Mass bunk me ksi ki attendance nato badhegi nato ghategi to mass bunk kr skte hain\n',
 'Yuval Lnct: This message was deleted\n',
 '+91 94246 48150: \u200eOpen this link to join my WhatsApp Group: https://chat.whatsapp.com/KjFJ30VehOpHWRnRi1rbgF\n',
 'Shantanu Lncts: Bhai koi gya hai ky cls??\n',
 'Vansh Lncts: Joke karta hai\n',
 '+91 94246 48150: "🔍 Join Our Quality Circle ! 🔍\n\nHello everyone,\n\nAre you passionate about how things actually work at industrial plants, how things work at ground level , practical implementation and teamwork?\n\n✨ We\'ve got an exciting opportunity for you! We are thrilled to invite you to join our Quality Circle , which is proudly associated with renowned brands like Godrej, Hershey\'s, Volvo, and Eicher.\n\n🌟 What You\'ll Get:\n\n✅- Stay updated on all the latest activities, events, and initiatives of our Quality Circle, in collaboration with industry leaders like Godrej, Hershey\'s, Volvo, and Eicher.\n\n✅- Gain exclusive opportunities to interact with professionals from these esteemed companies, allowing you to network and gain exposure to real-world industry practices.\n\n✅- Get access to valuable resources and insights on quality improvement.\n\n✅- Connect with like-minded individuals who share your passion for excellence.\n\nJoin us in our journey towards enhancing quality and making a positive impact, with the support of industry giants. To join, simply click the link below:\n\nhttps://chat.whatsapp.com/Ev9SMJ5d01I9Wm4QPsMeJF\nLet\'s work together to make a difference in our college and industry through quality initiatives. Your contribution matters, and the chance to interact with professionals from these companies is a unique opportunity! 🌟\n\nSee you in the group!\n\nBest regards,\nTeam"K-QCFI".\n',
 "+91 79996 77206 joined using this group's invite link\n",
 "+91 88252 16823 joined using this group's invite link\n",
 '+91 79996 77206: <Media omitted>\n',
 "Shalinder Pathak Lnct joined using this group's invite link\n",
 "+91 97536 63891 joined using this group's invite link\n",
 'Shantanu Lncts: Bhai C type charger hai ky class me ksi ke pass av????\nHai to de dena bhai log phn bs 18% charge hai🥲\n',
 '~\u202fRohan Choudhary added ~\u202fVenkat\n',
 '+91 62077 21723: This message was deleted\n',
 '+91 62077 21723: This message was deleted\n',
 'Srishti Hazra: <Media omitted>\n',
 'Srishti Hazra: <Media omitted>\n',
 'Shantanu Lncts: https://docs.google.com/forms/d/e/1FAIpQLSdm6_ZQUUbjClVUr_mPoRMB4VzruMVK0Hi6-pAc_PloY1-FFg/viewform?vc=0&c=0&w=1&flr=0\n',
 '~\u202fvivek indorkar added ~\u202fAnurag Rajput\n',
 '~\u202fAnurag Rajput added ~\u202fRaaz❤️\n',
 '+91 77488 92636: This message was deleted\n',
 'Shantanu Lncts: Bhai mai to lunch phle hi ni aya hun 😂\n',
 'Shantanu Lncts: Monday ka ky scene hai?\nKon kon aa rha?\n',
 'Sumit Lncts: Monday ko mass bunk hai\n',
 'Shantanu Lncts: POLL:\nMonday mass bunk?\nOPTION: Yes (40 votes)\nOPTION: No (1 vote)\n\n',
 'Shantanu Lncts: Bhai sab koi poll daal dena or real dalna \nSaturday k trh mt krna us din 22 baache aa gye the\nAgr koi ni ayega to attendance ksi ki jyegi bhi ni to nuksaan ksi ka ni hai\n',
 'Shantanu Lncts: Or aise bhi Data digital or do Oops hai us din🥲\n',
 'Vansh Lncts: declare kar do jo jayega usko baad me dekh lenghe\n',
 '~\u202fAnurag Rajput added ~\u202fAryan 💫\n',
 'Sumit Lncts: This message was deleted\n',
 'Sumit Lncts: Bilkul\n',
 '~\u202fsatyam added ~\u202fSATYAM ✨\n',
 'Vansh Lncts: Kam se Kam Pole pe clear kar do jisko Jana he padega\n',
 '+91 91311 08306: me to aaunga koi aao ya na aao\n',
 'Shantanu Lncts: Cancel hi kr dete hain bhai\nYe log nahi manega\nAa hi jayega\nTo mtlb nahi rhega mass bunk ka\n',
 '+91 99053 44129: Shi bola bhai ,,sb haramkhor h nii manege\n',
 '+91 91311 08306: i am just kidding me bhi nai raha\n',
 '+91 79996 77206: Areeh... Nhi aate h... Na attendance badhegi... Or na hi km hogi\n',
 '+91 77229 36199: Andi bandi shandi krdo\n',
 'Shantanu Lncts: <Media omitted>\n',
 'Shantanu Lncts: Phir bhi sab ayega bc\n',
 'Shantanu Lncts: You know what i mean☠️\n',
 'Sumit Lncts: Rhne de inka kuch nhi ho sakta\n',
 '+91 91311 08306: This message was deleted\n',
 '+91 99053 44129: Apan to bol rhe h Are h pura mehnat se dsa padhenge or placement lenge\n',
 'Shantanu Lncts: @917722936199 glt poll daal diya bsdk tu\n',
 'Shantanu Lncts: 🤦\u200d♂️\n',
 'Sumit Lncts: ...\n',
 '+91 77229 36199: Are dekha ni 🥲\n',
 'Shantanu Lncts: ANDI MANDI SHANDI JO MONDAY KO AAYA..\nAage sab smjhdar ho\n',
 'Shekhar LNCT: LNCTS Khel Mohotsav Badminton Tournament 2023\n\nWe are pleased to announce a Badminton Tournament on 26/10/2023.\n\nEntry Fee: ₹50\n\nParticipants are requested to register in advance. Grab your rackets and showcase your skills!\n\nFor further details and registration, please contact the following:\n(Faculty coordinator)\nAmol Upadhyay - 9893003004\n\n(Student coordinators)\nShekhar Suman - 6204082621\nYuval Varke - 9724614728\n\n\nThank you.\n',
 '+91 93291 37551: This message was deleted\n',
 "+91 93291 37551: To participate, please fill out this form: https://forms.gle/VHEZyBE5xfR6KVHv8\n\nLNCTS CSE CARROM TOURNAMENT\n🏆 Get Ready to Crown the Queen! 🏆\n\n📣 Exciting News LNCTS Students! 📣\n\n👑 LNCTS Carrom Championship - October 27th! 👑\n\n🤩 Are you ready to showcase your carrom skills and seize amazing prizes? 🤩\n\n📅 Mark your calendars for 27th October\n📍 LNCTS Campus\n\n🤑 Registration Fee: Only 50 Rupees\n\n🏆 Prizes await the Carrom Queens and Kings! 🏆\n\nDon't miss this thrilling showdown of precision and strategy! Whether you're a carrom maestro or a newcomer, everyone is invited to join in the fun. 🙌\n\nTo register, please contact the coordinators or use the provided link to fill out the form. Get ready to pocket your way to victory and rule the carrom board! 🎉\n\nSee you at the carrom table! 🤗 #LNCTS@CarromChampionship\n\nFor more information, reach out to the coordinators or visit the sports department. Let's make this tournament legendary! 💪\n\n👩\u200d🏫 Teacher Coordinator:\n Prof. Manisha Sen\n\n👥 Student Coordinators:\n\nLakshya Jain: 7877977590\nJahanvi Sable\nMayur Vishwakarma: 7987660323\nMuskan Chouksey\nAbhinav Barfa:  8982202717\nAsmit Janghela: 7723931135 \n\nNote: Only LNCTS CSE students can apply, and we also accept\xa0UPI\xa0payments.\n",
 '+91 93291 37551: <Media omitted>\n',
 'Shantanu Lncts: Bhai to kl cnfrm koi ni aa rha n??\n',
 '+91 77229 36199: Me to ni ara\n',
 'Samriddh Lnct: Bhai attendance achhi rakha kar, itni bheekh nhi maangni padegi\n',
 'Shantanu Lncts: Han to gyan mt dena bhai\n',
 'Samriddh Lnct: Aisi harkate karega toh gyan hi Dena padega\n',
 'Shantanu Lncts: Mai ni manta is gyan ko\n',
 'Harshita Lncts: Kl clg ana hai kya bhailogg\n',
 'Rudrasksh Lncts: Nai\n',
 '+91 89624 84906: Bilkul nhi\n',
 'Harshita Lncts: Voting krlo yarr koi mt aao\n',
 'Sahil Tale Lnct: POLL:\nFinal poll , kall aayoge ki nhi\nOPTION: Nhi (35 votes)\nOPTION: Aayunga (1 vote)\n\n',
 'Rudrasksh Lncts: Koi nai Ara yrr\n',
 'Sahil Tale Lnct: Aur koi aarha ho to batata do\n',
 'Harshita Lncts: Ha pliss\n',
 'Sahil Tale Lnct: Bhai sab vote kare\n',
 'Shantanu Lncts: Bhai poll mt daal, nahi to tujhe bhikhari bol diya jayega 💀\n',
 'Shubham Lnct: Jldi smjh aa gya bhai🙂\n',
 'Yuval Lnct: 3-4 bccho pe attendance lagegi ?\n',
 'Shantanu Lncts: Bhai ab gyani log gyan denge to smjhna to prega na☠️🙂\n',
 'Shubham Lnct: Kl hi de deta bhai samriddh tu gyaan Der kyo karayi bhai ko\n',
 'Shantanu Lncts: Are bhai bujurg log shi samy pr gyan dete hain\n',
 'Shekhar LNCT: Chill subham chiill\n',
 'Samriddh Lnct: Itne me offend ho gaya achha hua first year me nhi tha mere saath!\n',
 'Shantanu Lncts: Offend hota to tu dikh rha bhai\nMai to bakchodi kr rha hun💀\nOr rhi baat bakchodi ki to A-13 se jyda bakchod A-14 thi☠️😂\n',
 'Samriddh Lnct: Jaake DSA padh bhai!\n',

In [15]:
data = data.replace("\u202f", " ")

In [16]:
dates = re.findall(pattern, data)
dates

['7/25/23, 7:16 AM - ',
 '7/22/23, 1:10 PM - ',
 '7/25/23, 7:16 AM - ',
 '7/25/23, 7:54 AM - ',
 '7/25/23, 7:57 AM - ',
 '7/25/23, 8:24 AM - ',
 '7/25/23, 8:40 AM - ',
 '7/25/23, 8:45 AM - ',
 '7/25/23, 9:45 AM - ',
 '7/25/23, 10:25 AM - ',
 '7/25/23, 10:50 AM - ',
 '7/25/23, 10:55 AM - ',
 '7/25/23, 11:17 AM - ',
 '7/25/23, 11:18 AM - ',
 '7/25/23, 11:31 AM - ',
 '7/25/23, 11:50 AM - ',
 '7/25/23, 12:43 PM - ',
 '7/25/23, 12:43 PM - ',
 '7/25/23, 12:48 PM - ',
 '7/25/23, 12:48 PM - ',
 '7/25/23, 12:48 PM - ',
 '7/25/23, 12:54 PM - ',
 '7/25/23, 2:43 PM - ',
 '7/25/23, 2:43 PM - ',
 '7/25/23, 9:43 PM - ',
 '7/26/23, 2:46 PM - ',
 '7/26/23, 11:23 PM - ',
 '7/27/23, 1:10 AM - ',
 '7/31/23, 8:17 AM - ',
 '8/2/23, 10:34 PM - ',
 '8/8/23, 10:08 AM - ',
 '8/8/23, 10:09 AM - ',
 '8/8/23, 1:53 PM - ',
 '8/9/23, 7:50 PM - ',
 '8/11/23, 3:58 AM - ',
 '8/11/23, 4:01 AM - ',
 '8/11/23, 4:03 AM - ',
 '8/11/23, 4:10 AM - ',
 '8/12/23, 10:08 AM - ',
 '8/18/23, 1:16 PM - ',
 '8/20/23, 6:34 PM - ',
 '8/20/23, 9:13 PM - ',
 '8/28/23, 4:59 PM - ',
 '9/3/23, 10:20 AM - ',
 '9/5/23, 10:54 AM - ',
 '9/6/23, 10:21 AM - ',
 '9/6/23, 1:51 PM - ',
 '9/6/23, 3:34 PM - ',
 '9/6/23, 4:24 PM - ',
 '9/6/23, 4:24 PM - ',
 '9/6/23, 4:24 PM - ',
 '9/6/23, 4:26 PM - ',
 '9/6/23, 4:26 PM - ',
 '9/6/23, 4:26 PM - ',
 '9/6/23, 4:26 PM - ',
 '9/6/23, 4:28 PM - ',
 '9/6/23, 4:46 PM - ',
 '9/6/23, 7:20 PM - ',
 '9/8/23, 11:48 AM - ',
 '9/8/23, 11:49 AM - ',
 '9/8/23, 5:48 PM - ',
 '9/8/23, 10:32 PM - ',
 '9/11/23, 11:59 AM - ',
 '9/12/23, 6:35 PM - ',
 '9/12/23, 7:51 PM - ',
 '9/13/23, 4:05 PM - ',
 '9/13/23, 4:05 PM - ',
 '9/13/23, 4:05 PM - ',
 '9/13/23, 4:06 PM - ',
 '9/13/23, 4:06 PM - ',
 '9/13/23, 4:06 PM - ',
 '9/13/23, 4:06 PM - ',
 '9/13/23, 4:06 PM - ',
 '9/13/23, 4:07 PM - ',
 '9/13/23, 4:07 PM - ',
 '9/13/23, 4:07 PM - ',
 '9/13/23, 4:07 PM - ',
 '9/13/23, 4:07 PM - ',
 '9/13/23, 4:09 PM - ',
 '9/13/23, 6:33 PM - ',
 '9/13/23, 6:34 PM - ',
 '9/13/23, 6:34 PM - ',
 '9/13/23, 6:34 PM - ',
 '9/13/23, 6:34 PM - ',
 '9/13/23, 6:34 PM - ',
 '9/13/23, 6:36 PM - ',
 '9/13/23, 7:12 PM - ',
 '9/13/23, 9:26 PM - ',
 '9/13/23, 11:16 PM - ',
 '9/14/23, 5:41 PM - ',
 '9/14/23, 7:11 PM - ',
 '9/14/23, 7:11 PM - ',
 '9/19/23, 7:25 PM - ',
 '9/22/23, 6:20 AM - ',
 '9/22/23, 7:49 PM - ',
 '9/22/23, 7:49 PM - ',
 '9/23/23, 12:32 PM - ',
 '9/23/23, 1:23 PM - ',
 '9/23/23, 1:23 PM - ',
 '9/24/23, 1:42 PM - ',
 '9/26/23, 11:47 AM - ',
 '9/26/23, 11:47 AM - ',
 '9/26/23, 11:47 AM - ',
 '9/26/23, 11:48 AM - ',
 '9/26/23, 8:37 PM - ',
 '9/27/23, 2:23 PM - ',
 '9/27/23, 2:27 PM - ',
 '9/27/23, 6:13 PM - ',
 '9/27/23, 6:19 PM - ',
 '9/29/23, 9:23 PM - ',
 '9/29/23, 9:24 PM - ',
 '9/29/23, 9:24 PM - ',
 '9/29/23, 9:26 PM - ',
 '9/29/23, 9:27 PM - ',
 '9/29/23, 9:27 PM - ',
 '9/29/23, 9:39 PM - ',
 '9/29/23, 11:48 PM - ',
 '9/30/23, 5:34 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/3/23, 2:32 PM - ',
 '10/4/23, 7:52 PM - ',
 '10/6/23, 7:51 PM - ',
 '10/9/23, 3:04 PM - ',
 '10/10/23, 9:46 PM - ',
 '10/12/23, 3:47 PM - ',
 '10/12/23, 3:47 PM - ',
 '10/12/23, 3:47 PM - ',
 '10/12/23, 3:48 PM - ',
 '10/13/23, 2:52 PM - ',
 '10/13/23, 2:53 PM - ',
 '10/13/23, 2:54 PM - ',
 '10/13/23, 4:07 PM - ',
 '10/13/23, 10:48 PM - ',
 '10/14/23, 10:33 AM - ',
 '10/14/23, 11:01 AM - ',
 '10/14/23, 12:50 PM - ',
 '10/15/23, 2:58 PM - ',
 '10/16/23, 9:48 PM - ',
 '10/16/23, 9:50 PM - ',
 '10/16/23, 9:49 PM - ',
 '10/16/23, 11:04 PM - ',
 '10/16/23, 11:08 PM - ',
 '10/18/23, 11:48 AM - ',
 '10/18/23, 12:03 PM - ',
 '10/18/23, 1:21 PM - ',
 '10/18/23, 1:21 PM - ',
 '10/19/23, 9:32 PM - ',
 '10/19/23, 9:33 PM - ',
 '10/20/23, 10:45 AM - ',
 '10/20/23, 11:26 AM - ',
 '10/20/23, 12:18 PM - ',
 '10/21/23, 12:23 PM - ',
 '10/21/23, 12:26 PM - ',
 '10/21/23, 12:26 PM - ',
 '10/21/23, 12:30 PM - ',
 '10/21/23, 12:41 PM - ',
 '10/21/23, 12:42 PM - ',
 '10/21/23, 12:43 PM - ',
 '10/21/23, 12:46 PM - ',
 '10/21/23, 12:47 PM - ',
 '10/21/23, 12:52 PM - ',
 '10/21/23, 12:52 PM - ',
 '10/21/23, 12:56 PM - ',
 '10/21/23, 12:56 PM - ',
 '10/21/23, 12:58 PM - ',
 '10/21/23, 1:12 PM - ',
 '10/21/23, 1:14 PM - ',
 '10/21/23, 1:14 PM - ',
 '10/21/23, 1:15 PM - ',
 '10/21/23, 1:16 PM - ',
 '10/21/23, 1:16 PM - ',
 '10/21/23, 1:16 PM - ',
 '10/21/23, 1:16 PM - ',
 '10/21/23, 1:16 PM - ',
 '10/21/23, 1:16 PM - ',
 '10/21/23, 1:16 PM - ',
 '10/21/23, 1:17 PM - ',
 '10/21/23, 1:17 PM - ',
 '10/21/23, 1:17 PM - ',
 '10/21/23, 1:17 PM - ',
 '10/21/23, 1:18 PM - ',
 '10/21/23, 2:51 PM - ',
 '10/22/23, 5:41 PM - ',
 '10/22/23, 5:53 PM - ',
 '10/22/23, 5:53 PM - ',
 '10/22/23, 6:36 PM - ',
 '10/22/23, 6:37 PM - ',
 '10/22/23, 6:39 PM - ',
 '10/22/23, 6:40 PM - ',
 '10/22/23, 6:42 PM - ',
 '10/22/23, 6:42 PM - ',
 '10/22/23, 7:17 PM - ',
 '10/22/23, 7:18 PM - ',
 '10/22/23, 7:18 PM - ',
 '10/22/23, 7:18 PM - ',
 '10/22/23, 7:19 PM - ',
 '10/22/23, 7:19 PM - ',
 '10/22/23, 7:19 PM - ',
 '10/22/23, 7:19 PM - ',
 '10/22/23, 7:20 PM - ',
 '10/22/23, 7:34 PM - ',
 '10/22/23, 7:36 PM - ',
 '10/22/23, 7:37 PM - ',
 '10/22/23, 7:37 PM - ',
 '10/22/23, 7:40 PM - ',
 '10/22/23, 7:41 PM - ',
 '10/22/23, 7:42 PM - ',
 '10/22/23, 7:44 PM - ',
 '10/22/23, 7:46 PM - ',
 '10/22/23, 7:53 PM - ',
 '10/22/23, 7:54 PM - ',
 '10/22/23, 7:59 PM - ',
 '10/22/23, 8:04 PM - ',
 '10/22/23, 8:05 PM - ',
 '10/22/23, 8:06 PM - ',
 '10/22/23, 8:12 PM - ',
 '10/22/23, 8:13 PM - ',
 '10/22/23, 8:26 PM - ',
 '10/22/23, 8:27 PM - ',
 '10/22/23, 8:56 PM - ',
 '10/23/23, 12:36 PM - ',
 '10/23/23, 2:45 PM - ',
 '10/23/23, 2:56 PM - ',
 '10/23/23, 2:57 PM - ',
 '10/23/23, 2:57 PM - ',
 '10/24/23, 1:38 AM - ',
 '10/24/23, 1:38 AM - ',
 '10/26/23, 1:41 PM - ',
 '10/26/23, 1:41 PM - ',
 '10/26/23, 10:08 PM - ',
 '11/4/23, 10:29 AM - ',
 '11/4/23, 10:30 AM - ',
 '11/4/23, 10:31 AM - ',
 '11/4/23, 12:45 PM - ',
 '11/4/23, 8:10 PM - ',
 '11/4/23, 8:10 PM - ',
 '11/4/23, 8:11 PM - ',
 '11/4/23, 8:11 PM - ',
 '11/6/23, 11:02 AM - ',
 '11/7/23, 12:30 PM - ',
 '11/7/23, 3:49 PM - ',
 '11/7/23, 3:51 PM - ',
 '11/8/23, 8:13 PM - ',
 '11/11/23, 10:57 AM - ',
 '11/12/23, 8:32 AM - ',
 '11/12/23, 9:58 AM - ',
 '11/15/23, 8:38 PM - ',
 '11/15/23, 8:54 PM - ',
 '11/15/23, 8:54 PM - ',
 '11/15/23, 8:55 PM - ',
 '11/15/23, 8:56 PM - ',
 '11/15/23, 8:56 PM - ',
 '11/15/23, 8:56 PM - ',
 '11/15/23, 8:57 PM - ',
 '11/15/23, 8:57 PM - ',
 '11/15/23, 8:57 PM - ',
 '11/15/23, 8:57 PM - ',
 '11/15/23, 8:57 PM - ',
 '11/15/23, 8:57 PM - ',
 '11/15/23, 8:58 PM - ',
 '11/15/23, 8:58 PM - ',
 '11/15/23, 8:58 PM - ',
 '11/15/23, 8:58 PM - ',
 '11/15/23, 8:58 PM - ',
 '11/15/23, 8:59 PM - ',
 '11/15/23, 8:59 PM - ',
 '11/15/23, 8:59 PM - ',
 '11/15/23, 9:00 PM - ',
 '11/15/23, 9:01 PM - ',
 '11/15/23, 9:01 PM - ',
 '11/15/23, 9:01 PM - ',
 '11/15/23, 9:01 PM - ',
 '11/15/23, 9:02 PM - ',
 '11/15/23, 9:02 PM - ',
 '11/21/23, 1:17 PM - ',
 '11/21/23, 1:17 PM - ',
 '11/21/23, 2:56 PM - ',
 '11/21/23, 2:56 PM - ',
 '11/21/23, 2:56 PM - ',
 '11/21/23, 4:23 PM - ',
 '11/21/23, 4:23 PM - ',
 '11/23/23, 12:10 PM - ',
 '11/24/23, 8:06 PM - ',
 '11/29/23, 9:09 PM - ',
 '12/1/23, 8:31 PM - ',
 '12/8/23, 9:24 AM - ',
 '12/8/23, 9:24 AM - ',
 '12/8/23, 1:24 PM - ',
 '12/8/23, 1:24 PM - ',
 '12/15/23, 11:30 AM - ',
 '12/21/23, 2:59 PM - ',
 '12/23/23, 8:06 PM - ',
 '12/28/23, 10:34 PM - ',
 '12/28/23, 11:10 PM - ',
 '12/28/23, 11:10 PM - ',
 '12/28/23, 11:11 PM - ',
 '12/28/23, 11:11 PM - ',
 '1/1/24, 12:15 AM - ',
 '1/1/24, 12:28 AM - ',
 '1/1/24, 12:56 AM - ',
 '1/1/24, 7:33 PM - ',
 '1/1/24, 7:33 PM - ',
 '1/1/24, 7:33 PM - ',
 '1/1/24, 7:34 PM - ',
 '1/1/24, 7:34 PM - ',
 '1/1/24, 7:34 PM - ',
 '1/1/24, 7:34 PM - ',
 '1/1/24, 7:34 PM - ',
 '1/1/24, 7:34 PM - ',
 '1/1/24, 7:39 PM - ',
 '1/3/24, 9:00 PM - ',
 '1/4/24, 10:13 AM - ',
 '1/7/24, 4:47 PM - ',
 '1/7/24, 4:47 PM - ',
 '1/7/24, 4:47 PM - ',
 '1/7/24, 4:52 PM - ',
 '1/12/24, 7:58 PM - ',
 '1/12/24, 7:58 PM - ',
 '1/13/24, 2:26 PM - ',
 '1/15/24, 7:19 PM - ',
 '1/15/24, 7:20 PM - ',
 '1/15/24, 8:01 PM - ',
 '1/15/24, 8:02 PM - ',
 '1/18/24, 10:19 PM - ',
 '1/18/24, 10:19 PM - ',
 '1/18/24, 10:19 PM - ',
 '1/18/24, 10:19 PM - ',
 '1/18/24, 10:20 PM - ',
 '1/19/24, 3:59 PM - ',
 '1/19/24, 7:41 PM - ',
 '1/22/24, 11:57 PM - ',
 '1/22/24, 11:57 PM - ',
 '1/22/24, 11:58 PM - ',
 '1/28/24, 7:25 PM - ',
 '1/28/24, 7:25 PM - ',
 '1/28/24, 7:25 PM - ',
 '1/28/24, 7:25 PM - ',
 '1/30/24, 6:19 PM - ',
 '2/8/24, 7:30 PM - ',
 '2/8/24, 10:13 PM - ',
 '2/11/24, 2:05 PM - ',
 '2/12/24, 5:32 PM - ',
 '2/26/24, 4:47 PM - ',
 '3/4/24, 10:49 PM - ',
 '3/5/24, 3:52 PM - ',
 '3/5/24, 3:53 PM - ',
 '3/6/24, 9:40 AM - ',
 '3/6/24, 12:02 PM - ',
 '3/6/24, 9:35 PM - ',
 '3/7/24, 9:54 AM - ',
 '3/7/24, 10:07 AM - ',
 '3/7/24, 11:52 AM - ',
 '3/7/24, 2:01 PM - ',
 '3/7/24, 2:01 PM - ',
 '3/7/24, 2:01 PM - ',
 '3/7/24, 2:01 PM - ',
 '3/7/24, 2:01 PM - ',
 '3/7/24, 2:57 PM - ',
 '3/8/24, 5:34 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:32 PM - ',
 '3/8/24, 5:32 PM - ',
 '3/8/24, 5:32 PM - ',
 '3/8/24, 5:32 PM - ',
 '3/8/24, 5:32 PM - ',
 '3/8/24, 5:34 PM - ',
 '3/8/24, 5:34 PM - ',
 '3/8/24, 5:34 PM - ',
 '3/8/24, 5:34 PM - ',
 '3/8/24, 5:34 PM - ',
 '3/8/24, 5:34 PM - ',
 '3/8/24, 5:34 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:35 PM - ',
 '3/8/24, 5:36 PM - ',
 '3/8/24, 5:36 PM - ',
 '3/8/24, 5:36 PM - ',
 '3/8/24, 5:36 PM - ',
 '3/8/24, 5:36 PM - ',
 '3/8/24, 5:36 PM - ',
 '3/8/24, 5:37 PM - ',
 '3/8/24, 5:37 PM - ',
 '3/8/24, 5:37 PM - ',
 '3/8/24, 5:38 PM - ',
 '3/8/24, 5:38 PM - ',
 '3/8/24, 6:02 PM - ',
 '3/8/24, 6:05 PM - ',
 '3/8/24, 6:06 PM - ',
 '3/8/24, 6:07 PM - ',
 '3/8/24, 6:07 PM - ',
 '3/8/24, 6:11 PM - ',
 '3/8/24, 6:19 PM - ',
 '3/8/24, 6:19 PM - ',
 '3/8/24, 6:19 PM - ',
 '3/8/24, 6:19 PM - ',
 '3/8/24, 6:19 PM - ',
 '3/8/24, 7:38 PM - ',
 '3/8/24, 11:05 PM - ',
 '3/8/24, 11:05 PM - ',
 '3/8/24, 11:05 PM - ',
 '3/8/24, 11:05 PM - ',
 '3/8/24, 11:05 PM - ',
 '3/8/24, 11:05 PM - ',
 '3/8/24, 11:05 PM - ',
 '3/8/24, 11:06 PM - ',
 '3/8/24, 11:06 PM - ',
 '3/8/24, 11:06 PM - ',
 '3/8/24, 11:06 PM - ',
 '3/8/24, 11:06 PM - ',
 '3/8/24, 11:06 PM - ',
 '3/8/24, 11:07 PM - ',
 '3/8/24, 11:08 PM - ',
 '3/8/24, 11:11 PM - ',
 '3/8/24, 11:11 PM - ',
 '3/8/24, 11:12 PM - ',
 '3/8/24, 11:13 PM - ',
 '3/9/24, 10:35 AM - ',
 '3/9/24, 9:01 AM - ',
 '3/9/24, 9:02 AM - ',
 '3/9/24, 9:02 AM - ',
 '3/9/24, 9:03 AM - ',
 '3/9/24, 9:03 AM - ',
 '3/9/24, 9:03 AM - ',
 '3/9/24, 9:31 AM - ',
 '3/9/24, 9:32 AM - ',
 '3/9/24, 10:15 AM - ',
 '3/9/24, 10:15 AM - ',
 '3/9/24, 10:16 AM - ',
 '3/9/24, 10:17 AM - ',
 '3/9/24, 10:26 AM - ',
 '3/9/24, 10:39 AM - ',
 '3/9/24, 10:39 AM - ',
 '3/9/24, 11:07 AM - ',
 '3/9/24, 11:07 AM - ',
 '3/9/24, 11:07 AM - ',
 '3/9/24, 11:08 AM - ',
 '3/9/24, 11:11 AM - ',
 '3/9/24, 11:13 AM - ',
 '3/9/24, 3:39 PM - ',
 '3/11/24, 12:19 PM - ',
 '3/11/24, 1:49 PM - ',
 '3/13/24, 12:43 PM - ',
 '3/18/24, 9:45 PM - ',
 '4/1/24, 8:01 PM - ',
 '4/1/24, 9:56 PM - ',
 '4/2/24, 5:08 PM - ',
 '4/3/24, 10:35 AM - ',
 '4/3/24, 10:09 PM - ',
 '4/3/24, 10:12 PM - ',
 '4/12/24, 11:35 PM - ',
 '4/13/24, 1:25 PM - ',
 '4/13/24, 1:25 PM - ',
 '4/13/24, 1:25 PM - ',
 '4/13/24, 1:31 PM - ',
 '4/13/24, 1:31 PM - ',
 '4/14/24, 2:00 AM - ',
 '4/14/24, 2:01 AM - ',
 '4/16/24, 4:26 PM - ',
 '4/18/24, 4:11 PM - ',
 '4/22/24, 10:53 AM - ',
 '4/22/24, 11:21 AM - ',
 '4/22/24, 11:41 AM - ',
 '4/22/24, 11:44 AM - ',
 '4/23/24, 4:13 PM - ',
 '4/24/24, 12:58 PM - ',
 '4/25/24, 6:33 PM - ',
 '5/1/24, 12:06 AM - ',
 '5/1/24, 12:06 AM - ',
 '5/2/24, 2:12 PM - ',
 '5/2/24, 4:05 PM - ',
 '5/5/24, 1:16 PM - ',
 '5/6/24, 8:36 PM - ',
 '5/7/24, 9:35 PM - ',
 '5/7/24, 10:22 PM - ',
 '5/7/24, 10:23 PM - ',
 '5/7/24, 10:23 PM - ',
 '5/7/24, 10:23 PM - ',
 '5/7/24, 10:40 PM - ',
 '5/7/24, 11:01 PM - ',
 '5/7/24, 11:26 PM - ',
 '5/7/24, 11:27 PM - ',
 '5/7/24, 11:28 PM - ',
 '5/7/24, 11:49 PM - ',
 '5/9/24, 6:52 PM - ',
 '5/14/24, 11:01 PM - ',
 '5/15/24, 1:03 PM - ',
 '5/20/24, 6:37 PM - ',
 '5/21/24, 12:43 AM - ',
 '5/22/24, 6:09 PM - ',
 '5/23/24, 3:03 PM - ',
 '5/24/24, 1:05 AM - ',
 '5/24/24, 12:23 PM - ',
 '5/24/24, 5:09 PM - ',
 '5/24/24, 5:09 PM - ',
 '5/24/24, 5:09 PM - ',
 '5/24/24, 5:09 PM - ',
 '5/24/24, 5:10 PM - ',
 '5/24/24, 5:10 PM - ',
 '5/24/24, 5:10 PM - ',
 '5/24/24, 5:10 PM - ',
 '5/24/24, 5:10 PM - ',
 '5/24/24, 5:10 PM - ',
 '5/24/24, 5:10 PM - ',
 '5/24/24, 5:11 PM - ',
 '5/24/24, 5:11 PM - ',
 '5/24/24, 5:11 PM - ',
 '5/24/24, 5:11 PM - ',
 '5/24/24, 5:11 PM - ',
 '5/24/24, 5:11 PM - ',
 '5/24/24, 5:11 PM - ',
 '5/24/24, 5:12 PM - ',
 '5/24/24, 5:12 PM - ',
 '5/24/24, 6:10 PM - ',
 '6/13/24, 5:26 PM - ',
 '6/13/24, 5:26 PM - ',
 '6/14/24, 10:48 AM - ',
 '6/18/24, 8:28 PM - ',
 '6/18/24, 8:28 PM - ',
 '6/18/24, 8:28 PM - ',
 '6/19/24, 2:34 PM - ',
 '6/19/24, 2:37 PM - ',
 '6/19/24, 2:37 PM - ',
 '6/20/24, 1:54 PM - ',
 '6/20/24, 3:58 PM - ',
 '6/22/24, 4:40 PM - ',
 '6/22/24, 4:40 PM - ',
 '6/24/24, 5:18 PM - ',
 '6/26/24, 1:48 PM - ',
 '6/26/24, 1:51 PM - ',
 '6/26/24, 2:51 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/27/24, 2:49 PM - ',
 '6/28/24, 7:34 PM - ',
 '7/3/24, 12:25 PM - ',
 '7/3/24, 8:53 PM - ',
 '7/4/24, 4:06 PM - ',
 '7/5/24, 12:38 PM - ',
 '7/7/24, 11:23 PM - ',
 '7/7/24, 11:23 PM - ',
 '7/7/24, 11:23 PM - ',
 '7/7/24, 11:23 PM - ',
 '7/7/24, 11:23 PM - ',
 '7/7/24, 11:23 PM - ',
 '7/7/24, 11:23 PM - ',
 '7/7/24, 11:36 PM - ',
 '7/7/24, 11:54 PM - ',
 '7/7/24, 11:58 PM - ',
 '7/8/24, 12:08 AM - ',
 '7/8/24, 12:13 AM - ',
 '7/8/24, 12:13 AM - ',
 '7/8/24, 12:14 AM - ',
 '7/9/24, 11:54 PM - ',
 '7/10/24, 3:18 PM - ',
 '7/15/24, 9:13 AM - ',
 '7/15/24, 10:32 PM - ',
 '7/20/24, 1:47 PM - ',
 '7/25/24, 4:18 PM - ',
 '7/26/24, 12:20 PM - ',
 '7/30/24, 6:11 PM - ',
 '8/8/24, 5:52 PM - ',
 '8/15/24, 12:17 PM - ',
 '8/17/24, 7:58 AM - ',
 '8/17/24, 7:58 AM - ',
 '8/24/24, 2:28 PM - ',
 '8/28/24, 7:33 PM - ',
 '8/31/24, 12:20 PM - ',
 '9/2/24, 12:18 PM - ',
 '9/2/24, 12:18 PM - ',
 '9/2/24, 1:28 PM - ',
 '9/2/24, 1:50 PM - ',
 '9/3/24, 4:46 PM - ',
 '9/3/24, 4:46 PM - ',
 '9/5/24, 10:45 AM - ',
 '9/11/24, 11:28 AM - ',
 '9/12/24, 11:30 PM - ',
 '9/18/24, 9:15 PM - ',
 '9/18/24, 10:05 PM - ',
 '9/19/24, 12:23 PM - ',
 '9/25/24, 1:58 PM - ',
 '9/25/24, 1:59 PM - ',
 '9/26/24, 12:46 PM - ',
 '9/27/24, 6:19 PM - ',
 '9/29/24, 11:08 AM - ',
 '9/29/24, 11:33 PM - ',
 '9/29/24, 11:33 PM - ',
 '9/29/24, 11:33 PM - ',
 '9/29/24, 11:34 PM - ',
 '9/29/24, 11:34 PM - ',
 '9/29/24, 11:34 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:35 PM - ',
 '9/29/24, 11:36 PM - ',
 '9/29/24, 11:36 PM - ',
 '9/29/24, 11:36 PM - ',
 '9/29/24, 11:36 PM - ',
 '9/29/24, 11:36 PM - ',
 '9/29/24, 11:36 PM - ',
 '9/29/24, 11:37 PM - ',
 '9/29/24, 11:37 PM - ',
 '9/29/24, 11:37 PM - ',
 '9/29/24, 11:37 PM - ',
 '9/29/24, 11:37 PM - ',
 '9/29/24, 11:38 PM - ',
 '9/29/24, 11:38 PM - ',
 '9/29/24, 11:38 PM - ',
 '9/29/24, 11:39 PM - ',
 '9/29/24, 11:39 PM - ',
 '9/29/24, 11:39 PM - ',
 '9/29/24, 11:40 PM - ',
 '9/29/24, 11:40 PM - ',
 '9/29/24, 11:40 PM - ',
 '9/29/24, 11:40 PM - ',
 '9/29/24, 11:40 PM - ',
 '9/29/24, 11:40 PM - ',
 '9/29/24, 11:40 PM - ',
 '9/29/24, 11:41 PM - ',
 '9/29/24, 11:41 PM - ',
 '9/29/24, 11:41 PM - ',
 '9/29/24, 11:41 PM - ',
 '9/29/24, 11:41 PM - ',
 '9/29/24, 11:41 PM - ',
 '9/29/24, 11:42 PM - ',
 '9/29/24, 11:42 PM - ',
 '9/29/24, 11:42 PM - ',
 '9/29/24, 11:43 PM - ',
 '9/29/24, 11:43 PM - ',
 '9/29/24, 11:43 PM - ',
 '9/29/24, 11:43 PM - ',
 '9/29/24, 11:43 PM - ',
 '9/29/24, 11:43 PM - ',
 '9/29/24, 11:43 PM - ',
 '9/29/24, 11:43 PM - ',
 '9/29/24, 11:44 PM - ',
 '9/29/24, 11:45 PM - ',
 '9/29/24, 11:45 PM - ',
 '9/29/24, 11:45 PM - ',
 '9/29/24, 11:45 PM - ',
 '9/29/24, 11:45 PM - ',
 '9/29/24, 11:45 PM - ',
 '9/29/24, 11:45 PM - ',
 '9/29/24, 11:46 PM - ',
 '9/29/24, 11:46 PM - ',
 '9/29/24, 11:46 PM - ',
 '9/29/24, 11:46 PM - ',
 '9/29/24, 11:46 PM - ',
 '9/29/24, 11:46 PM - ',
 '9/29/24, 11:47 PM - ',
 '9/29/24, 11:47 PM - ',
 '9/29/24, 11:47 PM - ',
 '9/29/24, 11:48 PM - ',
 '9/29/24, 11:48 PM - ',
 '9/29/24, 11:48 PM - ',
 '9/29/24, 11:48 PM - ',
 '9/29/24, 11:48 PM - ',
 '9/29/24, 11:49 PM - ',
 '9/29/24, 11:49 PM - ',
 '9/29/24, 11:49 PM - ',
 '9/29/24, 11:49 PM - ',
 '9/29/24, 11:49 PM - ',
 '9/29/24, 11:50 PM - ',
 '9/29/24, 11:50 PM - ',
 '9/29/24, 11:50 PM - ',
 '9/29/24, 11:51 PM - ',
 '9/29/24, 11:51 PM - ',
 '9/29/24, 11:52 PM - ',
 '9/29/24, 11:52 PM - ',
 '9/29/24, 11:52 PM - ',
 '9/29/24, 11:53 PM - ',
 '9/30/24, 10:53 AM - ',
 '9/30/24, 10:53 AM - ',
 '9/30/24, 10:52 AM - ',
 '10/5/24, 1:39 PM - ',
 '10/5/24, 1:40 PM - ',
 '10/5/24, 1:40 PM - ',
 '10/5/24, 1:40 PM - ',
 '10/5/24, 1:41 PM - ',
 '10/5/24, 1:42 PM - ',
 '11/1/24, 12:04 AM - ',
 '11/7/24, 7:36 PM - ',
 '11/7/24, 7:37 PM - ',
 '11/7/24, 7:37 PM - ',
 '11/7/24, 7:38 PM - ',
 '11/7/24, 7:43 PM - ',
 '11/20/24, 11:46 AM - ',
 '11/28/24, 4:18 PM - ',
 '11/29/24, 3:44 PM - ',
 '12/1/24, 7:35 AM - ',
 '12/1/24, 12:23 PM - ',
 '12/2/24, 6:39 PM - ',
 '12/2/24, 6:39 PM - ',
 '12/2/24, 6:39 PM - ',
 '12/2/24, 6:40 PM - ',
 '12/2/24, 6:40 PM - ',
 '12/2/24, 6:40 PM - ',
 '12/2/24, 7:08 PM - ',
 '12/2/24, 7:08 PM - ',
 '12/2/24, 7:08 PM - ',
 '12/2/24, 9:58 PM - ',
 '12/2/24, 9:59 PM - ',
 '12/2/24, 10:02 PM - ',
 '12/2/24, 10:09 PM - ',
 '12/2/24, 10:10 PM - ',
 '12/2/24, 10:10 PM - ',
 '12/2/24, 10:10 PM - ',
 '12/2/24, 10:12 PM - ',
 '12/2/24, 10:15 PM - ',
 '12/2/24, 10:16 PM - ',
 '12/2/24, 10:16 PM - ',
 '12/2/24, 10:17 PM - ',
 '12/2/24, 10:17 PM - ',
 '12/2/24, 10:17 PM - ',
 '12/2/24, 10:18 PM - ',
 '12/2/24, 10:19 PM - ',
 '12/2/24, 10:20 PM - ',
 '12/2/24, 10:21 PM - ',
 '12/2/24, 10:21 PM - ',
 '12/2/24, 10:21 PM - ',
 '12/2/24, 10:21 PM - ',
 '12/2/24, 10:21 PM - ',
 '12/2/24, 10:21 PM - ',
 '12/2/24, 10:22 PM - ',
 '12/2/24, 10:22 PM - ',
 '12/2/24, 10:23 PM - ',
 '12/2/24, 10:23 PM - ',
 '12/2/24, 10:23 PM - ',
 '12/2/24, 10:23 PM - ',
 '12/2/24, 10:24 PM - ',
 '12/2/24, 10:24 PM - ',
 '12/2/24, 10:24 PM - ',
 '12/2/24, 10:25 PM - ',
 '12/2/24, 10:25 PM - ',
 '12/2/24, 10:26 PM - ',
 '12/2/24, 10:27 PM - ',
 '12/3/24, 12:08 AM - ',
 '12/3/24, 9:27 PM - ',
 '12/3/24, 9:27 PM - ',
 '12/3/24, 9:28 PM - ',
 '12/3/24, 9:28 PM - ',
 '12/3/24, 9:30 PM - ',
 '12/3/24, 9:30 PM - ',
 '12/3/24, 9:31 PM - ',
 '12/3/24, 9:31 PM - ',
 '12/3/24, 9:31 PM - ',
 '12/3/24, 9:32 PM - ',
 '12/3/24, 9:32 PM - ',
 '12/3/24, 9:41 PM - ',
 '12/3/24, 9:42 PM - ',
 '12/3/24, 9:42 PM - ',
 '12/3/24, 9:43 PM - ',
 '12/3/24, 9:43 PM - ',
 '12/4/24, 12:38 PM - ',
 '12/4/24, 12:38 PM - ',
 '12/4/24, 12:39 PM - ',
 '12/4/24, 12:41 PM - ',
 '12/4/24, 3:28 PM - ',
 '12/5/24, 12:40 PM - ',
 '12/5/24, 7:43 PM - ',
 '12/5/24, 7:43 PM - ',
 '12/5/24, 7:43 PM - ',
 '12/5/24, 7:43 PM - ',
 '12/5/24, 7:43 PM - ',
 '12/5/24, 7:45 PM - ',
 '12/5/24, 7:46 PM - ',
 '12/5/24, 7:46 PM - ',
 '12/5/24, 7:47 PM - ',
 '12/5/24, 7:48 PM - ',
 '12/5/24, 7:50 PM - ',
 '12/5/24, 8:01 PM - ',
 '12/5/24, 8:01 PM - ',
 '12/5/24, 8:01 PM - ',
 '12/5/24, 8:16 PM - ',
 '12/7/24, 5:08 PM - ',
 '12/7/24, 5:08 PM - ',
 '12/10/24, 9:51 PM - ',
 '12/10/24, 9:51 PM - ',
 '12/10/24, 9:52 PM - ',
 '12/10/24, 9:52 PM - ',
 '12/10/24, 9:53 PM - ',
 '12/11/24, 7:35 PM - ',
 '12/16/24, 2:05 PM - ',
 '12/19/24, 12:58 AM - ',
 '12/19/24, 3:04 PM - ',
 '12/23/24, 10:05 AM - ',
 '12/23/24, 10:05 AM - ',
 '12/31/24, 2:53 PM - ',
 '12/31/24, 2:54 PM - ',
 '12/31/24, 2:54 PM - ',

In [17]:
df = pd.DataFrame({'user_message': messages, 'message_date': dates})

df['message_date'] = df['message_date'].str.rstrip(' - ')

df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %I:%M %p', errors='coerce')

df.rename(columns={'message_date': 'date'}, inplace=True)
df.head()

                                        user_message                date
0  Messages and calls are end-to-end encrypted. N... 2023-07-25 07:16:00
1  ~ Tanishq Kirar created group "LNCTS CSE "C" U... 2023-07-22 13:10:00
2        You joined using this group's invite link\n 2023-07-25 07:16:00
3  +91 93049 97409 joined using this group's invi... 2023-07-25 07:54:00
4  Sahil Tale Lnct joined using this group's invi... 2023-07-25 07:57:00

In [18]:
df.shape

(1027, 2)

In [19]:
print(df.columns)  # Check actual column names

Index(['user_message', 'date'], dtype='object')

In [20]:
users = []
messages = []
for message in df['user_message']:
    entry = re.split(r'([\w\W]+?):\s', message)
    if entry[1:]:  # user name
        users.append(entry[1])
        messages.append(" ".join(entry[2:]))
    else:
        users.append('group_notification')
        messages.append(entry[0])

df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)

df.head()

,date,user,message
0,2023-07-25 07:16:00,group_notification,Messages and calls are end-to-end encrypted. N...
1,2023-07-22 13:10:00,group_notification,"~ Tanishq Kirar created group ""LNCTS CSE ""C"" U..."
2,2023-07-25 07:16:00,group_notification,You joined using this group's invite link\n
3,2023-07-25 07:54:00,group_notification,+91 93049 97409 joined using this group's invi...
4,2023-07-25 07:57:00,group_notification,Sahil Tale Lnct joined using this group's invi...

In [21]:
df['year'] = df['date'].dt.year

In [22]:
df.head()

,date,user,message,year
0,2023-07-25 07:16:00,group_notification,Messages and calls are end-to-end encrypted. N...,2023
1,2023-07-22 13:10:00,group_notification,"~ Tanishq Kirar created group ""LNCTS CSE ""C"" U...",2023
2,2023-07-25 07:16:00,group_notification,You joined using this group's invite link\n,2023
3,2023-07-25 07:54:00,group_notification,+91 93049 97409 joined using this group's invi...,2023
4,2023-07-25 07:57:00,group_notification,Sahil Tale Lnct joined using this group's invi...,2023

In [23]:
df[df['user'] == 'group_notification']

,date,user,message,year
0,2023-07-25 07:16:00,group_notification,Messages and calls are end-to-end encrypted. N...,2023
1,2023-07-22 13:10:00,group_notification,"~ Tanishq Kirar created group ""LNCTS CSE ""C"" U...",2023
2,2023-07-25 07:16:00,group_notification,You joined using this group's invite link\n,2023
3,2023-07-25 07:54:00,group_notification,+91 93049 97409 joined using this group's invi...,2023
4,2023-07-25 07:57:00,group_notification,Sahil Tale Lnct joined using this group's invi...,2023
...,...,...,...,...
767,2024-12-03 00:08:00,group_notification,~ Vikram added ~ Shamshad Ali\n,2024
830,2025-01-20 00:42:00,group_notification,~ Utkarsh changed the settings so all members ...,2025
831,2025-01-20 00:42:00,group_notification,~ Utkarsh changed the settings so only admins ...,2025
854,2025-02-07 16:53:00,group_notification,~ SUBODH 🙂 added Suryansh Lnct\n,2025
920,2025-03-07 12:54:00,group_notification,~ shivam... added ~ Jai Hind\n,2025

In [24]:
temp = df[df['user'] != 'group_notification']
temp = temp[temp['message'] != '<Media omitted>\n']

In [25]:
f = open('stop_hinglish.txt','r')
stop_words = f.read()
print(stop_words)

.
..
...
?
-
--
1
2
3
4
5
6
7
8
9
0
a
aadi
aaj
aap
aapne
aata
aati
aaya
aaye
ab
abbe
abbey
abe
abhi
able
about
above
accha
according
accordingly
acha
achcha
across
actually
after
afterwards
again
against
agar
ain
aint
ain't
aisa
aise
aisi
alag
all
allow
allows
almost
alone
along
already
also
although
always
am
among
amongst
an
and
andar
another
any
anybody
anyhow
anyone
anything
anyway
anyways
anywhere
ap
apan
apart
apna
apnaa
apne
apni
appear
are
aren
arent
aren't
around
arre
as
aside
ask
asking
at
aur
avum
aya
aye
baad
baar
bad
bahut
bana
banae
banai
banao
banaya
banaye
banayi
banda
bande
bandi
bane
bani
bas
bata
batao
bc
be
became
because
become
becomes
becoming
been
before
beforehand
behind
being
below
beside
besides
best
better
between
beyond
bhai
bheetar
bhi
bhitar
bht
bilkul
bohot
bol
bola
bole
boli
bolo
bolta
bolte
bolti
both
brief
bro
btw
but
by
came
can
cannot
cant
can't
cause
causes
certain
certainly
chahiye
chaiye
chal
chalega
chhaiye
clearly
c'mon
com
come
comes
could
couldn
couldnt
couldn't
d
de
dede
dega
degi
dekh
dekha
dekhe
dekhi
dekho
denge
dhang
di
did
didn
didnt
didn't
dijiye
diya
diyaa
diye
diyo
do
does
doesn
doesnt
doesn't
doing
done
dono
dont
don't
doosra
doosre
down
downwards
dude
dunga
dungi
during
dusra
dusre
dusri
dvaara
dvara
dwaara
dwara
each
edu
eg
eight
either
ek
else
elsewhere
enough
etc
even
ever
every
everybody
everyone
everything
everywhere
ex
exactly
example
except
far
few
fifth
fir
first
five
followed
following
follows
for
forth
four
from
further
furthermore
gaya
gaye
gayi
get
gets
getting
ghar
given
gives
go
goes
going
gone
good
got
gotten
greetings
guys
haan
had
hadd
hadn
hadnt
hadn't
hai
hain
hamara
hamare
hamari
hamne
han
happens
har
hardly
has
hasn
hasnt
hasn't
have
haven
havent
haven't
having
he
hello
help
hence
her
here
hereafter
hereby
herein
here's
hereupon
hers
herself
he's
hi
him
himself
his
hither
hm
hmm
ho
hoga
hoge
hogi
hona
honaa
hone
honge
hongi
honi
hopefully
hota
hotaa
hote
hoti
how
howbeit
however
hoyenge
hoyengi
hu
hua
hue
huh
hui
hum
humein
humne
hun
huye
huyi
i
i'd
idk
ie
if
i'll
i'm
imo
in
inasmuch
inc
inhe
inhi
inho
inka
inkaa
inke
inki
inn
inner
inse
insofar
into
inward
is
ise
isi
iska
iskaa
iske
iski
isme
isn
isne
isnt
isn't
iss
isse
issi
isski
it
it'd
it'll
itna
itne
itni
itno
its
it's
itself
ityaadi
ityadi
i've
ja
jaa
jab
jabh
jaha
jahaan
jahan
jaisa
jaise
jaisi
jata
jayega
jidhar
jin
jinhe
jinhi
jinho
jinhone
jinka
jinke
jinki
jinn
jis
jise
jiska
jiske
jiski
jisme
jiss
jisse
jitna
jitne
jitni
jo
just
jyaada
jyada
k
ka
kaafi
kab
kabhi
kafi
kaha
kahaa
kahaan
kahan
kahi
kahin
kahte
kaisa
kaise
kaisi
kal
kam
kar
kara
kare
karega
karegi
karen
karenge
kari
karke
karna
karne
karni
karo
karta
karte
karti
karu
karun
karunga
karungi
kaun
kaunsa
kayi
kch
ke
keep
keeps
keh
kehte
kept
khud
ki
kin
kine
kinhe
kinho
kinka
kinke
kinki
kinko
kinn
kino
kis
kise
kisi
kiska
kiske
kiski
kisko
kisliye
kisne
kitna
kitne
kitni
kitno
kiya
kiye
know
known
knows
ko
koi
kon
konsa
koyi
krna
krne
kuch
kuchch
kuchh
kul
kull
kya
kyaa
kyu
kyuki
kyun
kyunki
lagta
lagte
lagti
last
lately
later
le
least
lekar
lekin
less
lest
let
let's
li
like
liked
likely
little
liya
liye
ll
lo
log
logon
lol
look
looking
looks
ltd
lunga
m
maan
maana
maane
maani
maano
magar
mai
main
maine
mainly
mana
mane
mani
mano
many
mat
may
maybe
me
mean
meanwhile
mein
mera
mere
merely
meri
might
mightn
mightnt
mightn't
mil
mjhe
more
moreover
most
mostly
much
mujhe
must
mustn
mustnt
mustn't
my
myself
na
naa
naah
nahi
nahin
nai
name
namely
nd
ne
near
nearly
necessary
neeche
need
needn
neednt
needn't
needs
neither
never
nevertheless
new
next
nhi
nine
no
nobody
non
none
noone
nope
nor
normally
not
nothing
novel
now
nowhere
o
obviously
of
off
often
oh
ok
okay
old
on
once
one
ones
only
onto
or
other
others
otherwise
ought
our
ours
ourselves
out
outside
over
overall
own
par
pata
pe
pehla
pehle
pehli
people
per
perhaps
phla
phle
phli
placed
please
plus
poora
poori
provides
pura
puri
q
que
quite
raha
rahaa
rahe
rahi
rakh
rakha
rakhe
rakhen
rakhi
rakho
rather
re
really
reasonably
regarding
regardless
regards
rehte
rha
rhaa
rhe
rhi
ri
right
s
sa
saara
saare
saath
sab
sabhi
sabse
sahi
said
sakta
saktaa
sakte
sakti
same
sang
sara
sath
saw
say
saying
says
se
second
secondly
see
seeing
seem
seemed
seeming
seems
seen
self
selves
sensible
sent
serious
seriously
seven
several
shall
shan
shant
shan't
she
she's
should
shouldn
shouldnt
shouldn't
should've
si
sir
sir.
since
six
so
soch
some
somebody
somehow
someone
something
sometime
sometimes
somewhat
somewhere
soon
still
sub
such
sup
sure
t
tab
tabh
tak
take
taken
tarah
teen
teeno
teesra
teesre
teesri
tell
tends
tera
tere
teri
th
tha
than
thank
thanks
thanx
that
that'll
thats
that's
the
theek
their
theirs
them
themselves
then
thence
there
thereafter
thereby
therefore
therein
theres
there's
thereupon
these
they
they'd
they'll
they're
they've
thi
thik
thing
think
thinking
third
this
tho
thoda
thodi
thorough
thoroughly
those
though
thought
three
through
throughout
thru
thus
tjhe
to
together
toh
too
took
toward
towards
tried
tries
true
truly
try
trying
tu
tujhe
tum
tumhara
tumhare
tumhari
tune
twice
two
um
umm
un
under
unhe
unhi
unho
unhone
unka
unkaa
unke
unki
unko
unless
unlikely
unn
unse
until
unto
up
upar
upon
us
use
used
useful
uses
usi
using
uska
uske
usne
uss
usse
ussi
usually
vaala
vaale
vaali
vahaan
vahan
vahi
vahin
vaisa
vaise
vaisi
vala
vale
vali
various
ve
very
via
viz
vo
waala
waale
waali
wagaira
wagairah
wagerah
waha
wahaan
wahan
wahi
wahin
waisa
waise
waisi
wala
wale
wali
want
wants
was
wasn
wasnt
wasn't
way
we
we'd
well
we'll
went
were
we're
weren
werent
weren't
we've
what
whatever
what's
when
whence
whenever
where
whereafter
whereas
whereby
wherein
where's
whereupon
wherever
whether
which
while
who
whoever
whole
whom
who's
whose
why
will
willing
with
within
without
wo
woh
wohi
won
wont
won't
would
wouldn
wouldnt
wouldn't
y
ya
yadi
yah
yaha
yahaan
yahan
yahi
yahin
ye
yeah
yeh
yehi
yes
yet
you
you'd
you'll
your
you're
yours
yourself
yourselves
you've
yup

In [33]:
words = []

for message in temp['message']:
    for word in message.lower().split():
         if word not in stop_words:
            words.append(word)

In [34]:
from collections import Counter
pd.DataFrame(Counter(words).most_common(20))

             0   1
0      message  78
1      deleted  66
2       option  49
3       votes)  44
4         join  38
5        group  30
6         poll  29
7         link  22
8      college  22
9         mass  21
10  attendance  19
11        bunk  19
12       class  18
13         gya  17
14           😂  17
15           &  17
16  internship  16
17    exciting  15
18    whatsapp  15
19    students  15